def draw_hangman(lives):
    if lives == 6:
        print(" _______")
        print("|       |")
        print("|")
        print("|")
        print("|")
        print("|")
        print("|")
        print("|")
        print("----------")
    elif lives == 5:
        print(" _______")
        print("|       |")
        print("|       O")
        print("|")
        print("|")
        print("|")
        print("|")
        print("|")
        print("----------")
    elif lives == 4:
        print(" _______")
        print("|       |")
        print("|       O")
        print("|       |")
        print("|")
        print("|")
        print("|")
        print("|")
        print("----------")
    elif lives == 3:
        print(" _______")
        print("|       |")
        print("|       O")
        print("|      \\|")
        print("|")
        print("|")
        print("|")
        print("|")
        print("----------")
    elif lives == 2:
        print(" _______")
        print("|       |")
        print("|       O")
        print("|      \|/")
        print("|")
        print("|")
        print("|")
        print("|")
        print("----------")
    elif lives == 1:
        print(" _______")
        print("|       |")
        print("|       O")
        print("|      \|/")
        print("|       |")
        print("|")
        print("|")
        print("|")
        print("----------")
    elif lives == 0:
        print(" _______")
        print("|       |")
        print("|       O")
        print("|      \|/")
        print("|       |")
        print("|      / ")
        print("|")
        print("|")
        print("----------")
